
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh node-js --zone=us-central1-a --command='/bin/sh /home/yasar.iqbal/pull.sh'
